In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sqlite3

print("setup works")

setup works

In [2]:
import sys
sys.path.append("../src")
from returns import add_returns

conn = sqlite3.connect("../data/market.db")
prices = pd.read_sql_query("SELECT * FROM prices ORDER BY ticker, date", conn)
conn.close()

prices = add_returns(prices)
prices.head()

,ticker,date,open,high,low,close,adj_close,volume,simple_return,log_return
0,GLD,2014-01-02,117.930000,118.730003,117.750000,118.000000,118.000000,7551000,NaN,NaN
1,GLD,2014-01-03,118.639999,119.620003,118.589996,119.290001,119.290001,5874400,0.010932,0.010873
2,GLD,2014-01-06,119.760002,120.389999,117.110001,119.500000,119.500000,10106500,0.001760,0.001759
3,GLD,2014-01-07,118.459999,118.919998,118.129997,118.820000,118.820000,6433700,-0.005690,-0.005707
4,GLD,2014-01-08,117.989998,118.519997,117.500000,118.120003,118.120003,7428500,-0.005891,-0.005909

In [4]:
prices

,ticker,date,open,high,low,close,adj_close,volume,simple_return,log_return
0,GLD,2014-01-02,117.930000,118.730003,117.750000,118.000000,118.000000,7551000,NaN,NaN
1,GLD,2014-01-03,118.639999,119.620003,118.589996,119.290001,119.290001,5874400,0.010932,0.010873
2,GLD,2014-01-06,119.760002,120.389999,117.110001,119.500000,119.500000,10106500,0.001760,0.001759
3,GLD,2014-01-07,118.459999,118.919998,118.129997,118.820000,118.820000,6433700,-0.005690,-0.005707
4,GLD,2014-01-08,117.989998,118.519997,117.500000,118.120003,118.120003,7428500,-0.005891,-0.005909
...,...,...,...,...,...,...,...,...,...,...
22220,XLK,2026-08-12,189.470001,189.589996,188.330002,188.860001,188.860001,5887200,0.014885,0.014776
22221,XLK,2026-08-13,189.130005,191.740005,188.860001,190.770004,190.770004,4873900,0.010113,0.010063
22222,XLK,2026-08-14,191.139999,191.350006,189.250000,190.009995,190.009995,3634400,-0.003984,-0.003992
22223,XLK,2026-08-17,190.789993,191.750000,190.110001,190.320007,190.320007,6098500,0.001632,0.001630
22224,XLK,2026-08-18,186.289993,187.494995,184.330002,185.419998,185.419998,5030198,-0.025746,-0.026083

In [3]:
prices[prices["ticker"].isin(["GLD", "QQQ"])].iloc[3170:3180]

,ticker,date,open,high,low,close,adj_close,volume,simple_return,log_return
3170,GLD,2026-08-12,405.309998,407.359985,403.220001,404.920013,404.920013,10383100,0.009876,0.009828
3171,GLD,2026-08-13,402.170013,402.579987,398.279999,398.959991,398.959991,8695200,-0.014719,-0.014828
3172,GLD,2026-08-14,402.179993,403.329987,400.940002,401.480011,401.480011,6749800,0.006316,0.006297
3173,GLD,2026-08-17,402.339996,406.230011,402.179993,405.489990,405.489990,9578300,0.009988,0.009938
3174,GLD,2026-08-18,402.549988,404.299988,399.070007,400.329987,400.329987,6746893,-0.012725,-0.012807
3175,QQQ,2014-01-02,87.550003,87.580002,87.019997,87.269997,78.956863,29177500,NaN,NaN
3176,QQQ,2014-01-03,87.269997,87.349998,86.620003,86.639999,78.386856,35723700,-0.007219,-0.007245
3177,QQQ,2014-01-06,86.660004,86.760002,86.000000,86.320000,78.097366,32073100,-0.003693,-0.003700
3178,QQQ,2014-01-07,86.720001,87.250000,86.559998,87.120003,78.821159,25860600,0.009268,0.009225
3179,QQQ,2014-01-08,87.139999,87.550003,86.949997,87.309998,78.993073,27197400,0.002181,0.002179

In [ ]:
spy_log = prices[prices["ticker"] == "SPY"]["log_return"]
spy_log = spy_log.dropna()
plt.hist(spy_log, bins=100)
print(spy_log.kurtosis())